# git aliases
alias gco='git checkout'
alias gcp='git cherry-pick'
alias gcb='git checkout -b'
alias gb='git branch'
alias gbd='git branch -D'
alias gst='git status'
alias glg='git log'
alias ga='git add'
alias gfo='git fetch origin'
alias gpo='git pull origin'
alias gm='git merge'

alias cdnvim='cd ~/.config/nvim'
alias nvimconfig='cd ~/.config/nvim && nvim'
